# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image: danisla/hadoop:2.7.3
imagePullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.7.3

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

ranger:
  enabled: false
  host: ""
  port: 6080
  repoName: ""

  zookeeper:
    host: dave-sl-zookeeper-headless
    port: 2181

  auditing:
    summaryEnabled: false

    solr:
      enabled: true
      host: dave-sl-solr-headless
      port: 8983

    hdfs:
      enabled: false
      nameNode: dave-hb-hdfs-hdfs-nn
      nameNodePort: 9000

hdfs:
  nameNode:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "256Mi"
        cpu: "50m"
      limits:
        memory: "2048Mi"
        cpu: "500m"

  dataNode:
    replicas: 3

    pdbMinAvailable: 1

    resources:
      requests:
        memory: "512Mi"
        cpu: "50m"
      limits:
        memory: "2048Mi"
        cpu: "500m"


persistence:
  nameNode:
    enabled: true
    storageClass: "default"
    accessMode: ReadWriteOnce
    size: 5Gi

  dataNode:
    enabled: true
    name: hdfs-dn-data
    storageClass: "default"
    accessMode: ReadWriteOnce
    size: 10Gi
